DROP TRIGGER IF EXISTS deck_legal_after_cards ON deck_cards;
DROP TRIGGER IF EXISTS deck_legal_after_deck ON decks;
DROP FUNCTION IF EXISTS validate_deck_from_cards();
DROP FUNCTION IF EXISTS validate_deck_from_decks();
DROP FUNCTION IF EXISTS assert_deck_legal(uuid);
DROP TABLE IF EXISTS economy_transactions;
DROP TABLE IF EXISTS rewards;
DROP TABLE IF EXISTS idempotency_keys;
DROP TABLE IF EXISTS auth_refresh_history;
DROP TABLE IF EXISTS auth_sessions;
DROP TABLE IF EXISTS deck_cards;
DROP TABLE IF EXISTS decks;
DROP TABLE IF EXISTS player_champions;
DROP TABLE IF EXISTS player_cards;
DROP TABLE IF EXISTS seasons;
DROP TABLE IF EXISTS champions;
DROP TABLE IF EXISTS card_definitions;
DROP INDEX IF EXISTS one_active_ruleset;
DROP TABLE IF EXISTS rulesets;
DROP TABLE IF EXISTS player_profiles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS schema_migrations;
